window.charSets = {
  tr: 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split(''),
  en: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')
};

window.wordLists = {
  tr: [
    'at', 'kuş', 'kap', 'küp', 'fil', 'ayı', 'ot', 'çim', 'çam', 'gül',
    'kap', 'tuz', 'ut', 'ney', 'org', 'arp', 'saz', 'nem', 'kar', 'çiy',
    'don', 'göz', 'kul', 'diş', 'kas', 'dil', 'saç', 'tır', 'su', 'çay',
    'ip', 'gol', 'yüz', 'kaş', 'ev', 'oda', 'yem', 'kök', 'dal', 'bar',
    'not', 'sor', 'iş', 'köy', 'kent', 'el', 'kol', 'baş', 'bel', 'yol',
    'iş', 'kaz', 'hol', 'puf', 'duş', 'tül', 'ruj', 'far', 'köz', 'dut',
    'kedi', 'inek', 'koyun', 'keçi', 'kurt', 'ceyn', 'masa', 'tava', 'kupa', 'saat',
    'kase', 'şef', 'terz', 'iran', 'irak', 'kore', 'mısır', 'şili', 'peru', 'süt',
    'bal', 'kek', 'kazı', 'ekmek', 'lale', 'meşe', 'ağaç', 'boks', 'koşu', 'yoga',
    'tenis', 'judo', 'gri', 'bej', 'mor', 'sarı', 'lila', 'raf', 'vazo', 'soba',
    'ayna', 'halı', 'tabak', 'fırın', 'sehpa', 'keman', 'davul', 'flüt', 'bere', 'etek',
    'mayo', 'hırka', 'sis', 'kalp', 'mide', 'deri', 'kano', 'uçak', 'gemi', 'kayık',
    'nar', 'muz', 'elma', 'üzüm', 'erik', 'turp', 'roka', 'soda', 'kola', 'dart',
    'okey', 'kart', 'dama', 'chip', 'lens', 'fare', 'dağ', 'göl', 'kum', 'taş',
    'tepe', 'ada', 'koy', 'alın', 'dudak', 'çene', 'bot', 'mont', 'şort', 'bluz',
    'tayt', 'kafe', 'büfe', 'ödev', 'test', 'cam', 'yün', 'kız', 'kutu', 'ilçe',
    'tatlı', 'sırt', 'park', 'avlu', 'saha', 'okul', 'müze', 'cami', 'ofis', 'otel',
    'serçe', 'şahin', 'ördek', 'alo', 'güle', 'üç', 'dört', 'beş', 'altı', 'yedi',
    'tuz', 'kapı', 'dans', 'bale', 'sap', 'kıyı', 'buz', 'limon', 'banyo', 'askı',
    'biblo', 'stor', 'küvet', 'fırça', 'tarak', 'makas', 'eklem', 'hadi', 'hoş', 'olur',
    'simit', 'açma', 'pide', 'mantı', 'kısır', 'nohut', 'pırasa', 'lahana', 'taze',
    'kuru', 'nane', 'roka', 'sumak', 'susam', 'kaju', 'ceviz', 'incir', 'kivi', 'kök',
    'köpek', 'balık', 'kaplan', 'aslan', 'tilki', 'yılan', 'karga', 'kalem', 'araba', 'çanta',
    'cetvel', 'doktor', 'avukat', 'polis', 'yazar', 'mimar', 'kasap', 'pizza', 'çorba', 'kaktüs',
    'çınar', 'bambu', 'funda', 'kekik', 'futbol', 'güreş', 'karate', 'eskrim', 'sörf', 'mavi',
    'yeşil', 'siyah', 'beyaz', 'pembe', 'kahve', 'bordo', 'lamba', 'perde', 'çatal', 'kaşık',
    'bıçak', 'koltuk', 'yatak', 'dolap', 'gitar', 'kanun', 'kaval', 'atkı', 'kemer', 'ceket',
    'kazak', 'şapka', 'yelek', 'tunik', 'fular', 'yağmur', 'güneş', 'bulut', 'sıcak', 'soğuk',
    'beyin', 'kemik', 'burun', 'tırnak', 'damar', 'sinir', 'taksi', 'tren', 'metro', 'armut',
    'kiraz', 'çilek', 'kavun', 'incir', 'kabak', 'biber', 'soğan', 'havuç', 'marul', 'bamya',
    'ayran', 'kefir', 'boza', 'tavla', 'kablo', 'yazıcı', 'fare', 'modem', 'deniz', 'orman',
    'nehir', 'çöl', 'ova', 'toprak', 'vadi', 'bayır', 'plato', 'rıfkı', 'liman', 'kulak', 'boyun', 'yanak',
    'çizme', 'kaban', 'çiçek', 'meyve', 'kabuk', 'pazar', 'çarşı', 'liste', 'plan', 'çizim',
    'resim', 'cevap', 'sınav', 'proje', 'rapor', 'sunum', 'aile', 'komşu', 'konuk', 'yolcu',
    'turist', 'erken', 'geç', 'sonra', 'önce', 'hemen', 'yarın', 'dün', 'tuğla', 'beton',
    'ahşap', 'metal', 'kumaş', 'pamuk', 'bebek', 'kitap', 'dergi', 'kağıt', 'silgi', 'torba',
    'poşet', 'sokak', 'cadde', 'bölge', 'ülke', 'kıta', 'yemek', 'börek', 'pilav', 'kebap',
    'döner', 'sarma', 'sabah', 'akşam', 'öğle', 'ayak', 'omuz', 'göğüs', 'bahçe', 'köprü',
    'tünel', 'liman', 'sinema', 'market', 'fırın', 'banka', 'kartal', 'kaz', 'tavuk', 'selam',
    'sekiz', 'dokuz', 'üçgen', 'hoşça', 'şeker', 'duvar', 'tavan', 'zemin', 'çatı', 'balkon',
    'teras', 'dans', 'dalga', 'kıyı', 'liman', 'duman', 'sandal', 'ahbap', 'salon', 'kiler',
    'mutfak', 'yorgan', 'çarşaf', 'yastık', 'divan', 'kanepe', 'vitrin', 'sepet', 'saksı', 'heykel',
    'tablo', 'poster', 'panjur', 'lavabo', 'musluk', 'havlu', 'cımbız', 'törpü', 'maskar', 'allık',
    'parfüm', 'şampuan', 'krem', 'losyon', 'sirke', 'fişek', 'tamam', 'ender', 'sağol', 'bilek',
    'kumpir', 'poğaça', 'dolma', 'sarma', 'fasulye', 'mantar', 'kereviz', 'tarçın', 'kimyon', 'dereotu',
    'adaçayı', 'kekik', 'badem', 'fıstık', 'findık', 'hurma', 'erik', 'limon', 'yaban', 'üzüm',
    'kiraz', 'vişne', 'rende', 'asker', 'kürek', 'çadır', 'tavşan', 'defter', 'bardak', 'anahtar',
    'eczacı', 'fransa', 'italya', 'japonya', 'kanada', 'peynir', 'makarna', 'yumurta', 'yoğurt',
    'zeytin', 'orkide', 'basketb', 'atletiz', 'hentbol', 'kırmızı', 'lacivert', 'turkuaz',
    'piyano', 'gömlek', 'ayakkabı', 'eldiven', 'kravat', 'rüzgar', 'yıldırım', 'kamyon',
    'tramvay', 'portakal', 'domates', 'patates', 'ıspanak', 'bezelye', 'satranç', 'yapboz',
    'bilardo', 'körebe', 'seksek', 'klavye', 'kamera', 'hoparlör', 'tablet', 'drone',
    'ekran', 'router', 'batarya', 'sensör', 'adaptör', 'mağara', 'leylak', 'kirpik',
    'gözlük', 'terlik', 'tişört', 'tomurcuk', 'lokanta', 'pastane', 'dükkan', 'mektup',
    'ajanda', 'takvim', 'harita', 'makale', 'arkadaş', 'misafir', 'öğrenci', 'şimdi',
    'plastik', 'gazete', 'yemek', 'salata', 'meydan', 'hastane', 'tiyatro', 'baykuş',
    'lütfen', 'pardon', 'bir', 'iki', 'pencere', 'koridor', 'sandalet', 'kristal',
    'yorgan', 'battaniy', 'komodin', 'gardırop', 'çiçeklik', 'çerçeve', 'jaluzi',
    'fonluk', 'korniş', 'aynalı', 'sabunluk', 'ojelik', 'dişmacun', 'görüşürüz', 'eyvallah',
    'lahmacun', 'mercimek', 'barbunya', 'patlıcan', 'ıspanak', 'brokoli', 'enginar',
    'zencefil', 'zerdeçal', 'karabiber', 'maydanoz', 'fesleğen', 'biberiye', 'çörekotu',
    'haşhaş', 'anason', 'kestane', 'kuruüzüm', 'kayısı', 'şeftali', 'nektarin', 'mandalin',
    'greyfurt', 'avokado', 'böğürtlen', 'ahududu', 'karpuz', 'kavun', 'çilek',
    'formül', 'pergel', 'melodi', 'virgül', 'mevsim', 'yıldız', 'öğretmen', 'mühendis',
    'hemşire', 'sanatçı', 'almanya', 'brezilya', 'ispanya', 'norveç', 'voleybol',
    'süpürge', 'şifonyer', 'lahana', 'manzara', 'mengene', 'şırınga', 'kavanoz', 'iskelet',
    'kumanda', 'bilgisayar', 'televizyon', 'tornavida', 'motosiklet', 'helikopter',
    'saklambaç', 'yakartop', 'monitör', 'şelale', 'hayalperest', 'sindirim',
    'karnabahar', 'karanfil', 'sandalye', 'ameliyat', 'mikrofon', 'kerpeten', 'elektrik',
    'bulaşıkçı', 'buzdolabı', 'dondurucu', 'teknoloji', 'galibiyet', 'antrenman', 'matematik',
    'noktalama', 'enstrüman', 'tasarımcı', 'programcı', 'algoritma', 'enflasyon',
    'deflasyon', 'emeklilik', 'parlamento', 'demokrasi', 'medeniyet', 'psikoloji',
    'sosyoloji'
  ],
  en: [
    'at', 'go', 'up', 'on', 'is', 'it', 'in', 'or', 'pi', 'ax',
    'my', 'by', 'he', 'me', 'we', 'do', 'cup', 'box', 'pen', 'pan',
    'bug', 'tag', 'key', 'egg', 'oak', 'red', 'hot', 'cold', 'dew', 'eye',
    'ear', 'van', 'bus', 'pea', 'tea', 'bar', 'map', 'now', 'bag', 'arm',
    'leg', 'hey', 'bye', 'ice', 'pot', 'pie', 'cat', 'dog', 'bird', 'dish',
    'lion', 'cow', 'goat', 'fox', 'wolf', 'bear', 'crow', 'deer', 'chef', 'iran',
    'iraq', 'peru', 'milk', 'cake', 'soup', 'pine', 'rose', 'tree', 'yoga', 'judo',
    'gray', 'blue', 'lamp', 'sofa', 'bed', 'oven', 'lute', 'drum', 'harp', 'lyre',
    'pipe', 'hat', 'belt', 'cap', 'tie', 'snow', 'fog', 'rain', 'sun', 'wind',
    'nail', 'vein', 'taxi', 'ship', 'boat', 'pear', 'plum', 'fig', 'cola', 'rope',
    'dart', 'card', 'hide', 'ball', 'chip', 'lens', 'sand', 'sea', 'soil', 'hill',
    'cave', 'bay', 'face', 'lip', 'chin', 'neck', 'boot', 'coat', 'feed', 'seed',
    'root', 'leaf', 'bark', 'bud', 'cafe', 'shop', 'note', 'list', 'plan', 'test',
    'exam', 'soon', 'wood', 'wool', 'girl', 'baby', 'book', 'city', 'food', 'wrap',
    'noon', 'hand', 'foot', 'head', 'back', 'park', 'road', 'port', 'work', 'bank',
    'hawk', 'owl', 'goose', 'duck', 'four', 'five', 'six', 'nine', 'ten', 'call',
    'salt', 'door', 'wall', 'roof', 'stem', 'wave', 'port', 'hall', 'pouf', 'sofa',
    'pot', 'vase', 'tulle', 'sink', 'soap', 'comb', 'file', 'cool', 'bun', 'pie',
    'wrap', 'bean', 'leek', 'fresh', 'dry', 'mint', 'dill', 'sage', 'kiwi', 'sour',
    'rabbit', 'tiger', 'sheep', 'snake', 'table', 'glass', 'match', 'bowl', 'ruler', 'doctor',
    'nurse', 'tailor', 'writer', 'artist', 'korea', 'turkey', 'france', 'italy', 'japan',
    'brazil', 'canada', 'russia', 'greece', 'spain', 'egypt', 'chile', 'honey', 'banana',
    'bread', 'cheese', 'pizza', 'pasta', 'yogurt', 'olive', 'grass', 'tulip', 'maple',
    'thyme', 'boxing', 'tennis', 'karate', 'beige', 'green', 'black', 'white', 'pink',
    'brown', 'lilac', 'shelf', 'stove', 'flute', 'organ', 'piano', 'shirt', 'skirt', 'glove',
    'cloud', 'frost', 'tooth', 'heart', 'brain', 'stomach', 'bone', 'muscle', 'nose', 'tongue',
    'skin', 'hair', 'nerve', 'truck', 'canoe', 'train', 'plane', 'ferry', 'subway', 'cherry',
    'grape', 'melon', 'berry', 'radish', 'onion', 'carrot', 'soda', 'juice', 'syrup', 'chess',
    'puzzle', 'billiards', 'blind', 'hop', 'keyboard', 'camera', 'speaker', 'tablet', 'drone',
    'screen', 'router', 'battery', 'sensor', 'adapter', 'valley', 'desert', 'forest', 'river',
    'plain', 'ridge', 'plateau', 'harbor', 'cheek', 'wrist', 'ankle', 'elbow', 'knee',
    'sneaker', 'jacket', 'trousers', 'sweater', 'scarf', 'gloves', 'market', 'mall', 'square',
    'hospital', 'theater', 'museum', 'office', 'school', 'church', 'mosque', 'temple', 'hotel',
    'cinema', 'eagle', 'sparrow', 'pigeon', 'seagull', 'hello', 'goodbye', 'please', 'thanks',
    'sorry', 'one', 'two', 'three', 'seven', 'eight', 'window', 'ceiling', 'floor', 'balcony',
    'terrace', 'garden', 'bridge', 'tunnel', 'kitchen', 'bedroom', 'bathroom', 'living', 'dining',
    'closet', 'mirror', 'curtain', 'carpet', 'pillow', 'blanket', 'mattress', 'wardrobe', 'bookshelf',
    'candle', 'frame', 'vase', 'tray', 'bowl', 'plate', 'fork', 'spoon', 'knife', 'ladle',
    'toaster', 'blender', 'microwave', 'fridge', 'freezer', 'faucet', 'towel', 'brush', 'scissors',
    'razor', 'perfume', 'lotion', 'shampoo', 'conditioner', 'mascara', 'lipstick', 'eyeliner',
    'vinegar', 'mustard', 'ketchup', 'mayo', 'salad', 'sauce', 'gravy', 'steak', 'burger',
    'sandwich', 'taco', 'burrito', 'sushi', 'noodle', 'rice', 'potato', 'tomato', 'cucumber',
    'lettuce', 'spinach', 'broccoli', 'cauliflower', 'zucchini', 'eggplant', 'mushroom', 'pepper',
    'garlic', 'ginger', 'turmeric', 'cinnamon', 'parsley', 'basil', 'oregano', 'rosemary', 'thyme',
    'sesame', 'poppy', 'nutmeg', 'clove', 'saffron', 'almond', 'walnut', 'pecan', 'hazelnut',
    'pistachio', 'cashew', 'peanut', 'raisin', 'apricot', 'peach', 'nectarine', 'mango', 'pineapple',
    'coconut', 'avocado', 'blueberry', 'raspberry', 'blackberry', 'pomegranate', 'lemon', 'lime',
    'orange', 'tangerine', 'grapefruit', 'watermelon', 'cantaloupe', 'honeydew', 'strawberry',
    'apple', 'school', 'teacher', 'student', 'classroom', 'homework', 'exam', 'project', 'research',
    'library', 'computer', 'printer', 'scanner', 'monitor', 'mouse', 'software', 'hardware', 'network',
    'internet', 'website', 'database', 'algorithm', 'program', 'coding', 'developer', 'engineer',
    'designer', 'architect', 'scientist', 'researcher', 'analyst', 'manager', 'consultant', 'lawyer',
    'accountant', 'pharmacist', 'dentist', 'surgeon', 'veterinarian', 'pilot', 'captain', 'sailor',
    'soldier', 'officer', 'firefighter', 'paramedic', 'journalist', 'editor', 'publisher', 'musician',
    'actor', 'dancer', 'painter', 'sculptor', 'photographer', 'filmmaker', 'producer', 'director',
    'germany', 'australia', 'mexico', 'india', 'china', 'sweden', 'norway', 'finland', 'denmark',
    'poland', 'portugal', 'argentina', 'colombia', 'venezuela', 'thailand', 'malaysia', 'singapore',
    'indonesia', 'philippines', 'vietnam', 'africa', 'europe', 'asia', 'america', 'australia',
    'football', 'basketball', 'volleyball', 'baseball', 'hockey', 'cricket', 'rugby', 'golf',
    'swimming', 'cycling', 'running', 'wrestling', 'gymnastics', 'skating', 'skiing', 'surfing',
    'diving', 'sailing', 'rowing', 'archery', 'fencing', 'badminton', 'tabletennis', 'marathon',
    'triathlon', 'weightlifting', 'bodybuilding', 'crossfit', 'purple', 'yellow', 'orange', 'silver',
    'gold', 'bronze', 'copper', 'steel', 'iron', 'aluminum', 'plastic', 'rubber', 'leather', 'cotton',
    'silk', 'wool', 'linen', 'denim', 'velvet', 'satin', 'lace', 'nylon', 'polyester', 'bamboo',
    'hemp', 'jute', 'paper', 'cardboard', 'glass', 'ceramic', 'porcelain', 'clay', 'stone', 'marble',
    'granite', 'quartz', 'diamond', 'emerald', 'ruby', 'sapphire', 'topaz', 'amethyst', 'opal',
    'pearl', 'coral', 'amber', 'ivory', 'bone', 'shell', 'feather', 'fur', 'hide', 'wool', 'cashmere',
    'mohair', 'angora', 'alpaca', 'vicuna', 'llama', 'guanaco', 'muslin', 'chiffon', 'organza',
    'tulle', 'crepe', 'georgette', 'voile', 'batiste', 'canvas', 'duck', 'twill', 'sateen',
    'damask', 'brocade', 'jacquard', 'herringbone', 'houndstooth', 'plaid', 'tartan', 'gingham',
    'seersucker', 'madras', 'corduroy', 'velour', 'terry', 'fleece', 'flannel', 'gabardine',
    'tweed', 'suit', 'tuxedo', 'blazer', 'vest', 'parka', 'raincoat', 'windbreaker', 'overcoat',
    'trench', 'cape', 'poncho', 'shawl', 'cloak', 'robe', 'gown', 'dress', 'tunic', 'blouse',
    'top', 'tank', 'crop', 'hoodie', 'sweatshirt', 'cardigan', 'pullover', 'turtleneck', 'mock',
    'crew', 'vneck', 'polo', 'henley', 'buttonup', 'oxford', 'flannel', 'chambray', 'denim',
    'khaki', 'cargo', 'chino', 'legging', 'jogger', 'culotte', 'palazzo', 'capri', 'bermuda',
    'short', 'mini', 'midi', 'maxi', 'skort', 'romper', 'jumpsuit', 'overall', 'coverall',
    'apron', 'smock', 'labcoat', 'uniform', 'scrubs', 'toga', 'kimono', 'sari', 'kilt', 'turban',
    'hijab', 'veil', 'bonnet', 'beret', 'fedora', 'trilby', 'bowler', 'top hat', 'snapback',
    'beanie', 'visor', 'tam', 'cloche', 'pillbox', 'fascinator', 'headband', 'hairpin', 'clip',
    'comb', 'brush', 'roller', 'curler', 'dryer', 'straightener', 'iron', 'tong', 'wand',
    'gel', 'mousse', 'spray', 'pomade', 'wax', 'oil', 'serum', 'balm', 'cream', 'lotion',
    'toner', 'cleanser', 'moisturizer', 'exfoliant', 'mask', 'scrub', 'peel', 'essence',
    'ampoule', 'mist', 'sunscreen', 'foundation', 'concealer', 'primer', 'powder', 'blush',
    'bronzer', 'highlighter', 'contour', 'eyeshadow', 'eyeliner', 'mascara', 'brow', 'lipstick',
    'gloss', 'liner', 'stain', 'balm', 'nail polish', 'remover', 'cuticle', 'file', 'clipper',
    'buffer', 'pumice', 'loofah', 'sponge', 'puff', 'brush', 'blender', 'tweezer', 'curler',
    'mirror', 'scale', 'thermometer', 'bandage', 'gauze', 'tape', 'syringe', 'needle', 'pill',
    'capsule', 'tablet', 'syrup', 'drop', 'inhaler', 'spray', 'patch', 'cream', 'ointment',
    'gel', 'lotion', 'solution', 'suspension', 'emulsion', 'tincture', 'elixir', 'infusion',
    'decoction', 'extract', 'powder', 'granule', 'pellet', 'lozenge', 'troche', 'pastille',
    'suppository', 'enema', 'catheter', 'stethoscope', 'sphygmomanometer', 'otoscope', 'ophthalmoscope',
    'thermometer', 'pulse', 'oximeter', 'glucometer', 'ecg', 'eeg', 'mri', 'ct', 'xray',
    'ultrasound', 'endoscope', 'colonoscope', 'bronchoscope', 'laparoscope', 'arthroscope',
    'hysteroscope', 'cystoscope', 'speculum', 'forceps', 'scalpel', 'scissors', 'clamp',
    'retractor', 'suture', 'staple', 'drill', 'saw', 'laser', 'probe', 'curette', 'dilator',
    'specimen', 'biopsy', 'culture', 'swab', 'smear', 'slide', 'stain', 'microscope', 'centrifuge',
    'incubator', 'autoclave', 'sterilizer', 'pipette', 'burette', 'flask', 'beaker', 'vial',
    'tube', 'plate', 'dish', 'jar', 'bottle', 'can', 'tin', 'box', 'carton', 'pack', 'bag',
    'sack', 'pouch', 'envelope', 'folder', 'binder', 'notebook', 'journal', 'planner', 'calendar',
    'agenda', 'diary', 'log', 'record', 'file', 'document', 'report', 'memo', 'letter', 'email',
    'message', 'text', 'chat', 'post', 'tweet', 'blog', 'article', 'essay', 'story', 'novel',
    'poem', 'verse', 'rhyme', 'lyric', 'script', 'screenplay', 'manuscript', 'draft', 'outline',
    'summary', 'abstract', 'thesis', 'dissertation', 'paper', 'study', 'analysis', 'review',
    'critique', 'comment', 'feedback', 'survey', 'poll', 'questionnaire', 'form', 'application',
    'resume', 'cv', 'portfolio', 'profile', 'account', 'login', 'password', 'username', 'email',
    'phone', 'address', 'zip', 'code', 'number', 'id', 'card', 'ticket', 'pass', 'permit',
    'license', 'certificate', 'diploma', 'degree', 'award', 'medal', 'trophy', 'ribbon', 'plaque',
    'badge', 'pin', 'sticker', 'label', 'tag', 'barcode', 'qr', 'chip', 'sensor', 'tracker',
    'gps', 'map', 'compass', 'globe', 'atlas', 'guide', 'manual', 'handbook', 'textbook',
    'workbook', 'reader', 'anthology', 'encyclopedia', 'dictionary', 'thesaurus', 'almanac',
    'yearbook', 'catalog', 'brochure', 'pamphlet', 'leaflet', 'flyer', 'poster', 'banner',
    'sign', 'billboard', 'neon', 'led', 'screen', 'display', 'monitor', 'projector', 'tv',
    'radio', 'speaker', 'headphone', 'earphone', 'microphone', 'amplifier', 'mixer', 'recorder',
    'player', 'console', 'controller', 'joystick', 'keyboard', 'mouse', 'trackpad', 'stylus',
    'tablet', 'laptop', 'desktop', 'server', 'router', 'modem', 'switch', 'hub', 'cable',
    'wire', 'plug', 'socket', 'outlet', 'adapter', 'charger', 'battery', 'power', 'energy',
    'solar', 'wind', 'hydro', 'geothermal', 'nuclear', 'fossil', 'coal', 'oil', 'gas',
    'fuel', 'diesel', 'petrol', 'kerosene', 'propane', 'butane', 'methane', 'ethanol',
    'biodiesel', 'hydrogen', 'cell', 'panel', 'turbine', 'generator', 'reactor', 'dam',
    'reservoir', 'aquifer', 'well', 'spring', 'stream', 'creek', 'brook', 'pond', 'lake',
    'sea', 'ocean', 'gulf', 'bay', 'strait', 'channel', 'canal', 'river', 'delta', 'estuary',
    'lagoon', 'marsh', 'swamp', 'bog', 'fen', 'moor', 'heath', 'meadow', 'prairie', 'savanna',
    'steppe', 'tundra', 'taiga', 'forest', 'jungle', 'rainforest', 'desert', 'oasis', 'dune',
    'canyon', 'gorge', 'valley', 'basin', 'plateau', 'ridge', 'peak', 'summit', 'cliff',
    'crag', 'bluff', 'escarpment', 'mesa', 'butte', 'volcano', 'crater', 'lava', 'ash',
    'magma', 'geyser', 'hot spring', 'fumarole', 'cave', 'cavern', 'grotto', 'tunnel',
    'sinkhole', 'karst', 'reef', 'atoll', 'island', 'archipelago', 'peninsula', 'cape',
    'promontory', 'headland', 'point', 'beach', 'shore', 'coast', 'seaside', 'harbor',
    'port', 'dock', 'wharf', 'pier', 'jetty', 'breakwater', 'lighthouse', 'buoy', 'beacon',
    'anchor', 'rope', 'chain', 'net', 'trap', 'hook', 'line', 'sinker', 'float', 'bobber',
    'lure', 'bait', 'rod', 'reel', 'pole', 'spear', 'harpoon', 'trident', 'bow', 'arrow',
    'quiver', 'sling', 'catapult', 'cannon', 'gun', 'rifle', 'pistol', 'revolver', 'shotgun',
    'musket', 'carbine', 'bullet', 'cartridge', 'shell', 'powder', 'primer', 'fuse', 'grenade',
    'bomb', 'missile', 'rocket', 'torpedo', 'mine', 'explosive', 'detonator', 'dynamite',
    'tnt', 'c4', 'napalm', 'gas', 'chemical', 'biological', 'nuclear', 'weapon', 'armor',
    'shield', 'helmet', 'vest', 'plate', 'mail', 'chain', 'scale', 'leather', 'padding',
    'gauntlet', 'greave', 'sabatons', 'vambrace', 'pauldron', 'cuirass', 'tasset', 'fauld',
    'gorget', 'visor', 'sword', 'blade', 'dagger', 'knife', 'axe', 'hatchet', 'mace', 'club',
    'flail', 'hammer', 'spear', 'lance', 'pike', 'halberd', 'glaive', 'scythe', 'sickle',
    'staff', 'wand', 'rod', 'scepter', 'orb', 'crown', 'tiara', 'diadem', 'circlet', 'ring',
    'amulet', 'talisman', 'charm', 'pendant', 'necklace', 'bracelet', 'bangle', 'cuff', 'watch',
    'clock', 'timer', 'stopwatch', 'hourglass', 'sundial', 'calendar', 'almanac', 'ephemeris',
    'zodiac', 'horoscope', 'star', 'planet', 'moon', 'sun', 'comet', 'meteor', 'asteroid',
    'galaxy', 'nebula', 'cluster', 'constellation', 'orbit', 'eclipse', 'solstice', 'equinox',
    'tide', 'current', 'wave', 'ripple', 'surge', 'tsunami', 'hurricane', 'tornado', 'cyclone',
    'storm', 'thunder', 'lightning', 'rainbow', 'cloud', 'mist', 'fog', 'dew', 'frost', 'snow',
    'ice', 'sleet', 'hail', 'drizzle', 'shower', 'downpour', 'blizzard', 'gust', 'breeze',
    'gale', 'whirlwind', 'dust', 'sand', 'ash', 'smoke', 'fume', 'vapor', 'steam', 'haze',
    'smog', 'pollution', 'carbon', 'oxygen', 'nitrogen', 'hydrogen', 'helium', 'argon', 'neon',
    'krypton', 'xenon', 'radon', 'atom', 'molecule', 'ion', 'electron', 'proton', 'neutron',
    'quark', 'lepton', 'boson', 'photon', 'gluon', 'graviton', 'energy', 'mass', 'force',
    'motion', 'velocity', 'acceleration', 'momentum', 'friction', 'gravity', 'magnetism',
    'electricity', 'current', 'voltage', 'resistance', 'conductance', 'capacitance', 'inductance',
    'frequency', 'wavelength', 'amplitude', 'spectrum', 'radiation', 'infrared', 'ultraviolet',
    'microwave', 'radio', 'gamma', 'xray', 'light', 'color', 'red', 'orange', 'yellow', 'green',
    'blue', 'indigo', 'violet', 'white', 'black', 'gray', 'silver', 'gold', 'bronze', 'copper',
    'brass', 'iron', 'steel', 'aluminum', 'titanium', 'zinc', 'lead', 'tin', 'nickel', 'chrome',
    'mercury', 'platinum', 'palladium', 'rhodium', 'iridium', 'osmium', 'ruthenium', 'cobalt',
    'manganese', 'molybdenum', 'tungsten', 'vanadium', 'chromium', 'cadmium', 'arsenic', 'antimony',
    'bismuth', 'selenium', 'tellurium', 'iodine', 'fluorine', 'chlorine', 'bromine', 'astatine',
    'sulfur', 'phosphorus', 'silicon', 'boron', 'carbon', 'nitrogen', 'oxygen', 'hydrogen',
    'helium', 'lithium', 'beryllium', 'sodium', 'magnesium', 'potassium', 'calcium', 'rubidium',
    'strontium', 'cesium', 'barium', 'francium', 'radium', 'scandium', 'yttrium', 'lanthanum',
    'actinium', 'titanium', 'zirconium', 'hafnium', 'rutherfordium', 'vanadium', 'niobium', 'tantalum',
    'dubnium', 'chromium', 'molybdenum', 'tungsten', 'seaborgium', 'manganese', 'technetium', 'rhenium',
    'bohrium', 'iron', 'ruthenium', 'osmium', 'hassium', 'cobalt', 'rhodium', 'iridium', 'meitnerium',
    'nickel', 'palladium', 'platinum', 'darmstadtium', 'copper', 'silver', 'gold', 'roentgenium',
    'zinc', 'cadmium', 'mercury', 'copernicium', 'aluminum', 'gallium', 'indium', 'thallium',
    'nihonium', 'silicon', 'germanium', 'tin', 'lead', 'flerovium', 'phosphorus', 'arsenic', 'antimony',
    'bismuth', 'moscovium', 'sulfur', 'selenium', 'tellurium', 'polonium', 'livermorium', 'chlorine',
    'bromine', 'iodine', 'astatine', 'tennessine', 'fluorine', 'neon', 'argon', 'krypton', 'xenon',
    'radon', 'oganesson', 'element', 'compound', 'mixture', 'solution', 'suspension', 'colloid',
    'alloy', 'polymer', 'ceramic', 'composite', 'crystal', 'lattice', 'grain', 'fiber', 'foam',
    'gel', 'liquid', 'solid', 'gas', 'plasma', 'fluid', 'viscosity', 'density', 'pressure',
    'temperature', 'volume', 'mass', 'weight', 'length', 'width', 'height', 'depth', 'area',
    'surface', 'perimeter', 'circumference', 'radius', 'diameter', 'angle', 'degree', 'radian',
    'gradient', 'slope', 'curve', 'line', 'point', 'segment', 'ray', 'arc', 'circle', 'ellipse',
    'parabola', 'hyperbola', 'triangle', 'quadrilateral', 'pentagon', 'hexagon', 'heptagon',
    'octagon', 'nonagon', 'decagon', 'polygon', 'polyhedron', 'cube', 'cuboid', 'sphere',
    'cylinder', 'cone', 'pyramid', 'prism', 'tetrahedron', 'octahedron', 'dodecahedron',
    'icosahedron', 'torus', 'mobius', 'fractal', 'dimension', 'scalar', 'vector', 'tensor',
    'matrix', 'determinant', 'eigenvalue', 'eigenvector', 'transform', 'rotation', 'translation',
    'reflection', 'shear', 'scale', 'projection', 'map', 'function', 'domain', 'range', 'variable',
    'constant', 'parameter', 'equation', 'inequality', 'system', 'solution', 'root', 'zero',
    'intercept', 'slope', 'derivative', 'integral', 'limit', 'continuity', 'convergence',
    'divergence', 'series', 'sequence', 'sum', 'product', 'factor', 'multiple', 'divisor',
    'quotient', 'remainder', 'fraction', 'decimal', 'percent', 'ratio', 'proportion', 'rate',
    'unit', 'measure', 'metric', 'imperial', 'length', 'area', 'volume', 'mass', 'weight',
    'time', 'speed', 'velocity', 'acceleration', 'force', 'energy', 'power', 'work', 'torque',
    'momentum', 'impulse', 'pressure', 'density', 'temperature', 'heat', 'entropy', 'enthalpy',
    'frequency', 'wavelength', 'amplitude', 'period', 'cycle', 'phase', 'harmonic', 'resonance',
    'wave', 'particle', 'quantum', 'field', 'relativity', 'gravity', 'electromagnetism', 'strong',
    'weak', 'interaction', 'force', 'carrier', 'boson', 'fermion', 'quark', 'lepton', 'hadron',
    'baryon', 'meson', 'gluon', 'photon', 'graviton', 'higgs', 'supersymmetry', 'string',
    'brane', 'dimension', 'universe', 'multiverse', 'cosmos', 'galaxy', 'nebula', 'star',
    'planet', 'moon', 'asteroid', 'comet', 'meteor', 'blackhole', 'whitedwarf', 'neutronstar',
    'pulsar', 'quasar', 'supernova', 'bigbang', 'inflation', 'darkmatter', 'darkenergy',
    'radiation', 'background', 'horizon', 'event', 'singularity', 'wormhole', 'timespace',
    'continuum', 'causality', 'entropy', 'information', 'bit', 'byte', 'data', 'signal',
    'noise', 'bandwidth', 'frequency', 'modulation', 'amplitude', 'phase', 'carrier', 'channel',
    'protocol', 'network', 'internet', 'web', 'cloud', 'server', 'client', 'host', 'domain',
    'address', 'port', 'socket', 'packet', 'frame', 'datagram', 'segment', 'stream', 'flow',
    'traffic', 'bandwidth', 'latency', 'jitter', 'throughput', 'capacity', 'utilization',
    'performance', 'optimization', 'compression', 'encryption', 'decryption', 'authentication',
    'authorization', 'access', 'permission', 'role', 'user', 'group', 'admin', 'guest',
    'session', 'token', 'cookie', 'cache', 'buffer', 'queue', 'stack', 'heap', 'tree',
    'graph', 'node', 'edge', 'vertex', 'path', 'cycle', 'loop', 'branch', 'leaf', 'root',
    'depth', 'height', 'width', 'size', 'order', 'degree', 'connectivity', 'component',
    'cluster', 'partition', 'segment', 'fragment', 'slice', 'chunk', 'block', 'sector',
    'cluster', 'record', 'field', 'key', 'value', 'index', 'pointer', 'reference', 'link',
    'address', 'offset', 'base', 'limit', 'bound', 'range', 'scope', 'context', 'environment',
    'state', 'status', 'mode', 'condition', 'event', 'trigger', 'action', 'operation',
    'function', 'method', 'procedure', 'routine', 'task', 'process', 'thread', 'fiber',
    'coroutine', 'job', 'batch', 'stream', 'pipe', 'channel', 'port', 'socket', 'interface',
    'api', 'library', 'framework', 'platform', 'system', 'application', 'program', 'script',
    'code', 'source', 'binary', 'executable', 'module', 'package', 'bundle', 'archive',
    'file', 'folder', 'directory', 'path', 'drive', 'volume', 'partition', 'disk', 'tape',
    'card', 'chip', 'memory', 'ram', 'rom', 'cache', 'register', 'buffer', 'stack', 'heap',
    'storage', 'database', 'table', 'row', 'column', 'field', 'record', 'key', 'index',
    'query', 'view', 'schema', 'model', 'entity', 'attribute', 'relation', 'tuple',
    'join', 'union', 'intersection', 'difference', 'projection', 'selection', 'condition',
    'filter', 'sort', 'group', 'aggregate', 'sum', 'count', 'average', 'minimum', 'maximum',
    'median', 'mode', 'variance', 'deviation', 'correlation', 'regression', 'prediction',
    'estimation', 'interpolation', 'extrapolation', 'simulation', 'modeling', 'analysis',
    'synthesis', 'design', 'development', 'testing', 'debugging', 'profiling', 'monitoring',
    'logging', 'auditing', 'tracking', 'reporting', 'visualization', 'dashboard', 'chart',
    'graph', 'plot', 'diagram', 'map', 'image', 'video', 'audio', 'text', 'font', 'style',
    'format', 'layout', 'template', 'theme', 'skin', 'color', 'palette', 'gradient', 'shadow',
    'border', 'margin', 'padding', 'spacing', 'alignment', 'position', 'size', 'scale',
    'rotation', 'transform', 'transition', 'animation', 'effect', 'filter', 'blend', 'mask',
    'clip', 'crop', 'resize', 'rotate', 'flip', 'mirror', 'skew', 'warp', 'distort',
    'morph', 'blend', 'fade', 'slide', 'scroll', 'zoom', 'pan', 'tilt', 'rotate', 'spin',
    'bounce', 'shake', 'pulse', 'flash', 'glow', 'blink', 'flip', 'fold', 'curl', 'wave',
    'ripple', 'flow', 'stream', 'drift', 'glide', 'soar', 'hover', 'float', 'sink', 'drop',
    'fall', 'rise', 'climb', 'descend', 'land', 'takeoff', 'cruise', 'accelerate', 'decelerate',
    'brake', 'steer', 'navigate', 'pilot', 'drive', 'ride', 'walk', 'run', 'jump', 'leap',
    'hop', 'skip', 'crawl', 'slide', 'slip', 'trip', 'stumble', 'fall', 'roll', 'tumble',
    'flip', 'spin', 'twist', 'turn', 'pivot', 'swing', 'sway', 'rock', 'shake', 'vibrate',
    'pulse', 'beat', 'rhythm', 'tempo', 'meter', 'cadence', 'harmony', 'melody', 'chord',
    'note', 'scale', 'key', 'pitch', 'tone', 'timbre', 'volume', 'dynamics', 'articulation',
    'expression', 'phrase', 'motif', 'theme', 'variation', 'form', 'structure', 'texture',
    'layer', 'voice', 'part', 'section', 'movement', 'suite', 'symphony', 'concerto', 'sonata',
    'fugue', 'prelude', 'postlude', 'interlude', 'overture', 'finale', 'coda', 'reprise',
    'riff', 'loop', 'sample', 'beat', 'groove', 'hook', 'lick', 'fill', 'break', 'drop',
    'build', 'climax', 'resolve', 'release', 'tension', 'suspension', 'dissonance', 'consonance',
    'interval', 'octave', 'third', 'fifth', 'seventh', 'ninth', 'eleventh', 'thirteenth',
    'major', 'minor', 'diminished', 'augmented', 'dominant', 'tonic', 'subdominant', 'mediant',
    'submediant', 'leading', 'mode', 'ionian', 'dorian', 'phrygian', 'lydian', 'mixolydian',
    'aeolian', 'locrian', 'pentatonic', 'chromatic', 'atonal', 'serial', 'microtonal', 'quarter',
    'whole', 'half', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth',
    'tenth', 'eleventh', 'twelfth', 'thirteenth', 'fourteenth', 'fifteenth', 'sixteenth',
    'thirtysecond', 'sixtyfourth', 'note', 'rest', 'dot', 'tie', 'slur', 'staccato', 'legato',
    'marcato', 'tenuto', 'accent', 'fermata', 'trill', 'mordent', 'turn', 'appoggiatura',
    'acciaccatura', 'glissando', 'portamento', 'vibrato', 'tremolo', 'arpeggio', 'roll',
    'chord', 'cluster', 'block', 'broken', 'inversion', 'voicing', 'spacing', 'doubling',
    'cadence', 'authentic', 'plagal', 'deceptive', 'half', 'full', 'close', 'open', 'tonic',
    'dominant', 'subdominant', 'resolution', 'progression', 'sequence', 'cycle', 'turnaround',
    'modulation', 'pivot', 'key', 'signature', 'sharp', 'flat', 'natural', 'accidental',
    'clef', 'treble', 'bass', 'alto', 'tenor', 'soprano', 'baritone', 'mezzo', 'contralto',
    'countertenor', 'falsetto', 'head', 'chest', 'mix', 'belt', 'whistle', 'register', 'range',
    'tessitura', 'timbre', 'color', 'texture', 'blend', 'balance', 'dynamics', 'crescendo',
    'decrescendo', 'forte', 'piano', 'mezzo', 'fortissimo', 'pianissimo', 'sforzando', 'subito',
    'morendo', 'smorzando', 'rinforzando', 'espressivo', 'cantabile', 'dolce', 'maestoso',
    'giocoso', 'vivace', 'allegro', 'andante', 'adagio', 'largo', 'presto', 'moderato',
    'sostenuto', 'rubato', 'accelerando', 'ritardando', 'a tempo', 'metronome', 'beat',
    'pulse', 'tempo', 'meter', 'rhythm', 'syncopation', 'polyrhythm', 'crossrhythm', 'hemiola',
    'swing', 'shuffle', 'groove', 'feel', 'pocket', 'lock', 'tight', 'loose', 'laidback',
    'ahead', 'behind', 'rush', 'drag', 'push', 'pull', 'stretch', 'compress', 'expand',
    'contract', 'breathe', 'phrase', 'arc', 'shape', 'contour', 'line', 'melody', 'motif',
    'theme', 'variation', 'development', 'exposition', 'recapitulation', 'coda', 'intro',
    'verse', 'chorus', 'bridge', 'prechorus', 'postchorus', 'hook', 'refrain', 'outro',
    'tag', 'vamp', 'riff', 'ostinato', 'loop', 'sample', 'break', 'fill', 'solo', 'improv',
    'jam', 'session', 'gig', 'set', 'show', 'concert', 'recital', 'performance', 'rehearsal',
    'audition', 'casting', 'role', 'part', 'lead', 'support', 'ensemble', 'choir', 'chorus',
    'quartet', 'trio', 'duet', 'solo', 'accompaniment', 'orchestra', 'band', 'group', 'combo',
    'big band', 'chamber', 'symphony', 'philharmonic', 'conservatory', 'academy', 'school',
    'college', 'university', 'institute', 'center', 'foundation', 'society', 'association',
    'club', 'team', 'crew', 'squad', 'unit', 'division', 'department', 'branch', 'section',
    'sector', 'zone', 'region', 'area', 'district', 'neighborhood', 'community', 'village',
    'town', 'city', 'county', 'state', 'province', 'territory', 'country', 'nation', 'continent',
    'world', 'globe', 'earth', 'planet', 'solar', 'system', 'galaxy', 'universe', 'cosmos',
    'space', 'void', 'vacuum', 'infinity', 'eternity', 'time', 'past', 'present', 'future',
    'history', 'memory', 'record', 'archive', 'chronicle', 'annal', 'log', 'journal', 'diary',
    'memoir', 'biography', 'autobiography', 'story', 'tale', 'fable', 'myth', 'legend', 'epic',
    'saga', 'parable', 'allegory', 'anecdote', 'narrative', 'account', 'report', 'description',
    'explanation', 'exposition', 'argument', 'persuasion', 'rhetoric', 'discourse', 'dialogue',
    'conversation', 'discussion', 'debate', 'argument', 'dispute', 'controversy', 'conflict',
    'resolution', 'agreement', 'consensus', 'compromise', 'negotiation', 'mediation', 'arbitration',
    'settlement', 'deal', 'pact', 'treaty', 'accord', 'alliance', 'partnership', 'collaboration',
    'cooperation', 'coordination', 'integration', 'unification', 'merger', 'fusion', 'union',
    'federation', 'confederation', 'coalition', 'network', 'system', 'structure', 'framework',
    'model', 'paradigm', 'theory', 'hypothesis', 'conjecture', 'assumption', 'premise', 'axiom',
    'theorem', 'lemma', 'corollary', 'proof', 'evidence', 'data', 'fact', 'statistic', 'metric',
    'measure', 'indicator', 'index', 'benchmark', 'standard', 'criterion', 'norm', 'rule',
    'law', 'principle', 'doctrine', 'tenet', 'dogma', 'creed', 'belief', 'faith', 'religion',
    'spirituality', 'philosophy', 'ideology', 'worldview', 'perspective', 'viewpoint', 'stance “‘,’position’, ‘opinion’, ‘judgment’, ‘assessment’, ‘evaluation’, ‘appraisal’, ‘critique’, ‘review’, ‘feedback’, ‘comment’, ‘remark’, ‘statement’, ‘claim’, ‘assertion’, ‘argument’, ‘thesis’, ‘contention’, ‘proposition’, ‘hypothesis’, ‘theory’, ‘model’, ‘framework’, ‘paradigm’, ‘concept’, ‘idea’, ‘notion’, ‘thought’, ‘insight’, ‘vision’, ‘dream’, ‘goal’, ‘objective’, ‘aim’, ‘purpose’, ‘mission’, ‘vision’, ‘strategy’, ‘plan’, ‘tactic’, ‘approach’, ‘method’, ‘technique’, ‘procedure’, ‘process’, ‘system’, ‘mechanism’, ‘tool’, ‘instrument’, ‘device’, ‘machine’, ‘engine’, ‘motor’, ‘gear’, ‘lever’, ‘pulley’, ‘wheel’, ‘axle’, ‘spring’, ‘coil’, ‘valve’, ‘pump’, ‘fan’, ‘blade’, ‘propeller’, ‘turbine’, ‘piston’, ‘cylinder’, ‘crank’, ‘cam’, ‘shaft’, ‘bearing’, ‘belt’, ‘chain’, ‘sprocket’, ‘clutch’, ‘brake’, ‘shock’, ‘strut’, ‘damper’, ‘suspension’, ‘chassis’, ‘frame’, ‘body’, ‘shell’, ‘hull’, ‘fuselage’, ‘wing’, ‘tail’, ‘fin’, ‘rudder’, ‘aileron’, ‘flap’, ‘slat’, ‘spoiler’, ‘elevator’, ‘stabilizer’, ‘rotor’, ‘blade’, ‘hub’, ‘mast’, ‘boom’, ‘spar’, ‘rib’, ‘stringer’, ‘skin’, ‘panel’, ‘bulkhead’, ‘firewall’, ‘cockpit’, ‘cabin’, ‘compartment’, ‘hold’, ‘bay’, ‘door’, ‘hatch’, ‘ramp’, ‘ladder’, ‘stair’, ‘rail’, ‘handle’, ‘knob’, ‘latch’, ‘lock’, ‘key’, ‘bolt’, ‘nut’, ‘screw’, ‘rivet’, ‘weld’, ‘joint’, ‘seam’, ‘bond’, ‘glue’, ‘tape’, ‘clip’, ‘clamp’, ‘hook’, ‘loop’, ‘strap’, ‘buckle’, ‘zipper’, ‘button’, ‘snap’, ‘velcro’, ‘thread’, ‘yarn’, ‘fiber’, ‘fabric’, ‘cloth’, ‘material’, ‘texture’, ‘pattern’, ‘weave’, ‘knit’, ‘stitch’, ‘sew’, ‘hem’, ‘pleat’, ‘fold’, ‘crease’, ‘wrinkle’, ‘ridge’, ‘groove’, ‘channel’, ‘slot’, ‘hole’, ‘cavity’, ‘pocket’, ‘pouch’, ‘sack’, ‘bag’, ‘pack’, ‘case’, ‘box’, ‘crate’, ‘carton’, ‘container’, ‘vessel’, ‘tank’, ‘drum’, ‘barrel’, ‘keg’, ‘jug’, ‘jar’, ‘bottle’, ‘flask’, ‘vial’, ‘tube’, ‘can’, ‘tin’, ‘pot’, ‘pan’, ‘skillet’, ‘griddle’, ‘wok’, ‘kettle’, ‘teapot’, ‘coffeepot’, ‘urn’, ‘pitcher’, ‘carafe’, ‘decanter’, ‘goblet’, ‘mug’, ‘cup’, ‘saucer’, ‘bowl’, ‘plate’, ‘dish’, ‘tray’, ‘platter’, ‘board’, ‘block’, ‘slab’, ‘sheet’, ‘panel’, ‘tile’, ‘brick’, ‘stone’, ‘rock’, ‘pebble’, ‘gravel’, ‘sand’, ‘dust’, ‘powder’, ‘grain’, ‘seed’, ‘nut’, ‘bean’, ‘pea’, ‘lentil’, ‘rice’, ‘wheat’, ‘corn’, ‘oat’, ‘barley’, ‘rye’, ‘millet’, ‘quinoa’, ‘buckwheat’, ‘sorghum’, ‘flour’, ‘meal’, ‘dough’, ‘batter’, ‘paste’, ‘cream’, ‘sauce’, ‘gravy’, ‘soup’, ‘stew’, ‘broth’, ‘stock’, ‘consomme’, ‘puree’, ‘mash’, ‘jam’, ‘jelly’, ‘preserve’, ‘marmalade’, ‘chutney’, ‘relish’, ‘pickle’, ‘salsa’, ‘dip’, ‘spread’, ‘butter’, ‘margarine’, ‘oil’, ‘fat’, ‘lard’, ‘tallow’, ‘ghee’, ‘cream’, ‘cheese’, ‘yogurt’, ‘custard’, ‘pudding’, ‘mousse’, ‘gelatin’, ‘aspic’, ‘sorbet’, ‘sherbet’, ‘ice cream’, ‘frozen’, ‘yogurt’, ‘parfait’, ‘granita’, ‘slush’, ‘shake’, ‘smoothie’, ‘juice’, ‘nectar’, ‘syrup’, ‘soda’, ‘tonic’, ‘water’, ‘tea’, ‘coffee’, ‘cocoa’, ‘chocolate’, ‘milk’, ‘cream’, ‘latte’, ‘espresso’, ‘cappuccino’, ‘mocha’, ‘macchiato’, ‘americano’, ‘breve’, ‘flat white’, ‘cortado’, ‘galao’, ‘lungo’, ‘ristretto’, ‘drip’, ‘pour over’, ‘french press’, ‘aeropress’, ‘siphon’, ‘cold brew’, ‘nitro’, ‘decaf’, ‘herbal’, ‘green’, ‘black’, ‘white’, ‘oolong’, ‘puerh’, ‘matcha’, ‘chai’, ‘rooibos’, ‘mate’, ‘infusion’, ‘tisane’, ‘decoction’, ‘blend’, ‘leaf’, ‘bud’, ‘twig’, ‘bark’, ‘root’, ‘flower’, ‘petal’, ‘stamen’, ‘pistil’, ‘pollen’, ‘nectar’, ‘honey’, ‘wax’, ‘comb’, ‘hive’, ‘bee’, ‘wasp’, ‘hornet’, ‘ant’, ‘termite’, ‘beetle’, ‘butterfly’, ‘moth’, ‘dragonfly’, ‘damselfly’, ‘grasshopper’, ‘cricket’, ‘locust’, ‘cicada’, ‘aphid’, ‘ladybug’, ‘firefly’, ‘mantis’, ‘scorpion’, ‘spider’, ‘mite’, ‘tick’, ‘centipede’, ‘millipede’, ‘worm’, ‘leech’, ‘slug’, ‘snail’, ‘clam’, ‘oyster’, ‘mussel’, ‘scallop’, ‘crab’, ‘lobster’, ‘shrimp’, ‘prawn’, ‘crayfish’, ‘krill’, ‘barnacle’, ‘coral’, ‘anemone’, ‘jellyfish’, ‘starfish’, ‘urchin’, ‘cucumber’, ‘sponge’, ‘tunicate’, ‘lancelet’, ‘lamprey’, ‘hagfish’, ‘shark’, ‘ray’, ‘skate’, ‘chimaera’, ‘sturgeon’, ‘gar’, ‘bowfin’, ‘eel’, ‘herring’, ‘anchovy’, ‘sardine’, ‘salmon’, ‘trout’, ‘char’, ‘whitefish’, ‘grayling’, ‘smelt’, ‘pike’, ‘muskellunge’, ‘pickerel’, ‘carp’, ‘minnow’, ‘loach’, ‘bitterling’, ‘sucker’, ‘catfish’, ‘characin’, ‘tetra’, ‘hatchetfish’, ‘piranha’, ‘silverfish’, ‘killifish’, ‘mosquitofish’, ‘livebearer’, ‘guppy’, ‘molly’, ‘platy’, ‘swordtail’, ‘silverside’, ‘needlefish’, ‘halfbeak’, ‘flyingfish’, ‘ricefish’, ‘stickleback’, ‘pipefish’, ‘seahorse’, ‘trumpetfish’, ‘cornetfish’, ‘snipefish’, ‘shrimpfish’, ‘dragonet’, ‘goby’, ‘sleeper’, ‘blenny’, ‘gunnel’, ‘prickleback’, ‘wolffish’, ‘eelblenny’, ‘clinid’, ‘sandlance’, ‘wrasse’, ‘parrotfish’, ‘damselfish’, ‘clownfish’, ‘sergeant’, ‘angelfish’, ‘butterflyfish’, ‘surgeonfish’, ‘tang’, ‘triggerfish’, ‘filefish’, ‘pufferfish’, ‘boxfish’, ‘cowfish’, ‘trunkfish’, ‘sunfish’, ‘mola’, ‘barracuda’, ‘mackerel’, ‘tuna’, ‘bonito’, ‘swordfish’, ‘marlin’, ‘sailfish’, ‘needlefish’, ‘saury’, ‘cutlassfish’, ‘scabbardfish’, ‘hairtail’, ‘oarfish’, ‘lanternfish’, ‘lightfish’, ‘pearlfish’, ‘cusk’, ‘cod’, ‘haddock’, ‘pollock’, ‘hake’, ‘burbot’, ‘rattail’, ‘grenadier’, ‘moray’, ‘conger’, ‘garden eel’, ‘snipe eel’, ‘gulper’, ‘pelican eel’, ‘swallower’, ‘spikefish’, ‘dory’, ‘boarfish’, ‘armorhead’, ‘remora’, ‘jacksmelt’, ‘mullet’, ‘goatfish’, ‘weever’, ‘sculpin’, ‘lumpsucker’, ‘snailfish’, ‘stonefish’, ‘lionfish’, ‘scorpionfish’, ‘flathead’, ‘gurnard’, ‘searobin’, ‘bigeye’, ‘cardinalfish’, ‘soldierfish’, ‘squirrelfish’, ‘sweeper’, ‘flashlightfish’, ‘pineconefish’, ‘knightfish’, ‘driftfish’, ‘medusafish’, ‘squaretail’, ‘tripletail’, ‘lookdown’, ‘harvestfish’, ‘butterfish’, ‘pomfret’, ‘sergeantfish’, ‘rabbitfish’, ‘spinefoot’, ‘moorish idol’, ‘discus’, ‘batfish’, ‘spadefish’, ‘chub’, ‘grunt’, ‘sweetlips’, ‘porgy’, ‘snapper’, ‘emperor’, ‘fusilier’, ‘bream’, ‘croaker’, ‘drum’, ‘weakfish’, ‘kingfish’, ‘cobia’, ‘jack’, ‘trevally’, ‘scad’, ‘amberjack’, ‘yellowtail’, ‘runner’, ‘permit’, ‘pompano’, ‘palometa’, ‘leatherjacket’, ‘tripletail’, ‘tilefish’, ‘bluefish’, ‘ladyfish’, ‘tarpon’, ‘bonefish’, ‘alewife’, ‘menhaden’, ‘shad’, ‘milkfish’, ‘chanos’, ‘lizardfish’, ‘sandfish’, ‘greenling’, ‘lingcod’, ‘flatfish’, ‘flounder’, ‘sole’, ‘halibut’, ‘turbot’, ‘plaice’, ‘dab’, ‘brill’, ‘megrim’, ‘tonguefish’, ‘hogchoker’, ‘sanddab', ‘windowpane', ‘lefteye', ‘righteye', ‘dogfish’, ‘angelshark’, ‘sawshark’, ‘guitarfish', ‘electric ray', ‘stingray', ‘manta', ‘devil ray', ‘skate', ‘chimaera', ‘ratfish', 'rabbitfish', 'coelacanth', 'lungfish', 'bichir', 'reedfish', 'ropefish', 'knifefish', 'featherback', 'arowana', 'arapaima', 'pirarucu', 'butterflyfish', 'angelfish', 'damselfish', 'clownfish', 'sergeant', 'wrasse', 'parrotfish', 'goby', 'blenny', 'dragonet', 'sculpin', 'stickleback', 'pipefish', 'seahorse', 'triggerfish', 'pufferfish', 'filefish', 'boxfish', 'sunfish', 'barracuda', 'mackerel', 'tuna', 'swordfish', 'marlin', 'sailfish', 'cod', 'haddock', 'pollock', 'hake', 'moray', 'conger', 'burbot', 'rattail', 'grenadier', 'lanternfish', 'lightfish', 'pearlfish', 'oarfish', 'gulper', 'swallower', 'spikefish', 'dory', 'remora', 'jacksmelt', 'mullet', 'goatfish', 'weever', 'lumpsucker', 'snailfish', 'stonefish', 'lionfish', 'scorpionfish', 'bigeye', 'cardinalfish', 'soldierfish', 'squirrelfish', 'sweeper'
  ]
};

window.hiddenWordLists = {
  tr: {
    5: ['asker', 'balta', 'rende', 'kürek', 'çadır', 'çekiç'],
    6: ['formül', 'melodi', 'mevsim', 'pergel', 'virgül', 'yıldız'],
    7: ['iskelet', 'kavanoz', 'kumanda', 'manzara', 'mengene', 'şırınga'],
    8: ['ameliyat', 'elektrik', 'karanfil', 'kerpeten', 'mikrofon', 'sandalye'],
    9: ['algoritma', 'antrenman', 'bulaşıkçı', 'buzdolabı', 'deflasyon', 'demokrasi', 'dondurucu', 'emeklilik', 'enflasyon', 'enstrüman', 'galibiyet', 'matematik', 'medeniyet', 'noktalama', 'parlamento', 'programcı', 'psikoloji', 'sosyoloji', 'tasarımcı', 'teknoloji']
  },
  en: {
    5: ['diamond', 'flask', 'golem', 'index', 'joker', 'koala', 'mango', 'noble', 'pencil', 'pilot', 'quilt', 'radio']
        6: ['formül', 'melodi', 'mevsim', 'pergel', 'virgül', 'yıldız'],
      7: ['iskelet', 'kavanoz', 'kumanda', 'manzara', 'mengene', 'şırınga'],
      8: ['ameliyat', 'elektrik', 'karanfil', 'kerpeten', 'mikrofon', 'sandalye'],
      9: ['algoritma', 'antrenman', 'bulaşıkçı', 'buzdolabı', 'deflasyon', 'demokrasi', 'dondurucu', 'emeklilik', 'enflasyon', 'enstrüman', 'galibiyet', 'matematik', 'medeniyet', 'noktalama', 'parlamento', 'programcı', 'psikoloji', 'sosyoloji', 'tasarımcı', 'teknoloji']

  }
};