const wordListTr = [
	'at', 'ot', 'su', 'ip', 'el', 'iş', 'ev', 'al', 'an', 'ar', 'as', 'aş', 'av', 'ay', 'az', 'ağ',
	'ak', 'ah', 'be', 'bu', 'ek', 'en', 'er', 'es', 'et', 'ey', 'fa', 'iç', 'il', 'in', 'is', 'it', 
	'iz', 'of', 'oh', 'ok', 'ol', 'on', 'öf', 'ön', 'öt', 'öz','uç', 'uf', 'un', 'us','üç', 'ün', 'üs', 
	've', 'ya',

	'kuş', 'kap', 'küp', 'fil', 'ayı', 'çim', 'çam', 'gül', 'tuz', 'ud', 'ney', 'org', 'arp', 'saz',
	'nem', 'kar', 'çiy', 'don', 'göz', 'kul', 'diş', 'kas', 'dil', 'saç', 'tır', 'çay', 'gol', 'yüz',
	'kaş', 'oda', 'yem', 'kök', 'dal', 'bar', 'not', 'sor', 'köy', 'kol', 'baş', 'bel', 'yol', 'hol',
	'puf', 'duş', 'tül', 'ruj', 'far', 'köz', 'dut', 'süt', 'bal', 'kek', 'nar', 'muz', 'göl', 'kum',
	'taş', 'koy', 'cam', 'yün', 'kız', 'sap', 'buz', 'alo', 'aşk', 'boy', 'can', 'cep', 'cin',
	'çan', 'çit', 'dar', 'dış', 'diz', 'duy', 'fan', 'faz', 'fen', 'fön', 'gaz', 'gen', 'güç', 'hak',
	'ham', 'han', 'har', 'hat', 'haz', 'her', 'hiç', 'jet', 'jön', 'kal', 'kan', 'kir', 'kör', 'kot',
	'kur', 'kür', 'laf', 'lan', 'mat', 'maç', 'mil', 'mor', 'mum', 'nam', 'net',
	'nil', 'pil', 'pul', 'rol', 'saf', 'sem', 'sen', 'ser', 'set', 'sır', 'şah', 'şal', 'şan', 'şef',
	'şek', 'şen', 'şey', 'şok', 'tok', 'top', 'tür', 'vah', 'var', 'vay', 'yaz', 'yıl', 'yük',
	'zar', 'zat', 'zil', 'zor', 'sis', 

	'kedi', 'inek', 'masa', 'tava', 'kupa', 'saat', 'kase', 'iran', 'ırak', 'kore', 'mısır', 'şili',
	'peru', 'kazı', 'lale', 'meşe', 'ağaç', 'boks', 'koşu', 'yoga', 'tenis', 'vazo', 'soba', 'mayo',
	'kano', 'uçak', 'gemi', 'roka', 'soda', 'kola', 'dart', 'okey', 'kart', 'dama', 'dağ',
	'tepe', 'ada', 'alın', 'çene', 'bot', 'mont', 'şort', 'tayt', 'kafe', 'ödev', 'test', 'park',
	'saha', 'müze', 'cami', 'otel', 'dans', 'bale', 'kıyı', 'hadi', 'hoş', 'açma', 'pide', 'taze',
	'kuru', 'nane', 'kaju', 'adıl', 'adet', 'afet', 'akıl', 'akım', 'akçe', 'akor', 'akse',
	'alan', 'alem', 'alet', 'alev', 'amfi', 'amip', 'anaç', 'anıt', 'arka', 'arpa',  'asit',
	'asma', 'atık', 'atlet', 'ayva', 'baba', 'bacı', 'bank', 'bant', 'bari', 'baro', 'bebe', 'beka',
	'bela', 'bere', 'beze', 'biat', 'bina', 'bira', 'bire', 'boru', 'boya', 'bölü',  'burs',
	'büfe', 'cadı', 'cefa', 'celp', 'cilt', 'cins', 'cips', 'ciro', 'cop', 'çaba', 'çare',
	'çeri', 'çete', 'çile', 'çini', 'çita', 'çivi', 'çizı', 'dahi', 'dair', 'dana',
	'dara', 'darb', 'data', 'dede', 'define', 'deha', 'deli', 'delil', 'denk', 'dere',
	'koyun', 'keçi', 'kurt', 'ekmek', 'judo', 'gri', 'bej', 'sarı', 'lila', 'ayna', 'halı',
	'tabak', 'fırın', 'sehpa', 'keman', 'davul', 'flüt', 'hırka', 'kalp', 'mide', 'kayık',
	'elma', 'üzüm', 'erik', 'turp', 'dudak', 'bluz', 'kutu', 'ilçe', 'tatlı', 'sırt', 'avlu',
	'okul', 'ofis', 'serçe', 'şahin', 'ördek', 'güle', 'kapı', 'limon', 'banyo', 'askı', 'biblo',
	'stor', 'küvet', 'fırça', 'tarak', 'makas', 'eklem', 'simit', 'mantı', 'kısır', 'nohut',
	'sumak', 'susam', 'ceviz', 'incir', 'kivi', 'köpek', 'balık', 'tilki', 'yılan', 'karga', 'kalem',
	'araba', 'çanta', 'polis', 'yazar', 'mimar', 'kasap', 'pizza', 'çorba', 'çınar', 'bambu', 'funda',
	'kekik', 'güreş', 'siyah', 'beyaz', 'pembe', 'kahve', 'bordo', 'lamba', 'perde', 'çatal', 'kaşık',
	'bıçak', 'yatak', 'dolap', 'gitar', 'kanun', 'kaval', 'atkı', 'kemer', 'ceket', 'kazak', 'şapka',
	'yelek', 'tunik', 'fular', 'güneş', 'bulut', 'sıcak', 'soğuk', 'beyin', 'kemik', 'burun', 'damar',
	'sinir', 'taksi', 'tren', 'metro', 'armut', 'kiraz', 'çilek', 'kavun', 'kabak', 'biber', 'soğan',
	'havuç', 'marul', 'bamya', 'ayran', 'kefir', 'boza', 'tavla', 'kablo', 'fare', 'modem', 'deniz',
	'orman', 'nehir', 'çöl', 'toprak', 'vadi', 'bayır', 'rıfkı', 'liman', 'kulak', 'boyun', 'yanak',
	'çizme', 'kaban', 'çiçek', 'meyve', 'kabuk', 'pazar', 'çarşı', 'liste', 'plan', 'çizim', 'resim',
	'cevap', 'sınav', 'proje', 'rapor', 'sunum', 'aile', 'komşu', 'konuk', 'yolcu', 'erken', 'sonra',
	'önce', 'hemen', 'yarın', 'tuğla', 'beton', 'ahşap', 'metal', 'kumaş', 'pamuk', 'bebek', 'kitap',
	'dergi', 'kağıt', 'silgi', 'torba', 'sokak', 'cadde', 'bölge', 'ülke', 'kıta', 'yemek', 'börek',
	'pilav', 'kebap', 'döner', 'sarma', 'sabah', 'akşam', 'öğle', 'ayak', 'omuz', 'bahçe', 'köprü',
	'tünel', 'sinema', 'banka', 'selam', 'sekiz', 'dokuz', 'hoşça', 'şeker', 'duvar', 'tavan',
	'zemin', 'çatı', 'dalga', 'duman', 'ahbap', 'salon', 'kiler', 'divan', 'sepet', 'saksı', 'heykel',
	'tablo', 'panjur', 'havlu', 'törpü', 'allık', 'krem', 'sirke', 'fişek', 'tamam', 'ender', 'sağol',
	'bilek', 'dolma', 'tarçın', 'badem', 'fıstık', 'hurma', 'vişne', 'rende', 'asker',
	'kürek', 'çadır', 'defter',
	'kaplan', 'aslan', 'cetvel', 'doktor', 'avukat', 'kaktüs', 'futbol', 'karate', 'eskrim', 'koltuk',
	'yağmur', 'tırnak', 'findık', 'yaban', 'bardak', 'anahtar', 'eczacı', 'fransa', 'italya', 'japonya',
	'kanada', 'peynir', 'yoğurt', 'zeytin', 'orkide', 'gömlek', 'kravat', 'rüzgar', 'kamyon', 'satranç',
	'yapboz', 'körebe', 'seksek', 'kamera', 'tablet', 'batarya', 'sensör', 'kirpik', 'gözlük', 'terlik',
	'tişört', 'dükkan', 'mektup', 'ajanda', 'takvim', 'harita', 'makale', 'misafir', 'şimdi', 'gazete',
	'salata', 'meydan', 'baykuş', 'lütfen', 'pardon', 'pencere', 'aktris', 'albümin',
	'amblem', 'anket', 'anlam', 'asmak', 'aşama', 'bahane', 'bakkal', 'balkon', 'banker',
	'basket', 'bağcık', 'benzin', 'berber', 'besteci', 'beygir', 'bezelye', 'bilet',
	'bilişim', 'bisiklet', 'bitki', 'boylam', 'bozkır', 'böbrek', 'böcek', 'bucak', 'bulgur',
	'bulmaca', 'burslu', 'büro', 'bütçe', 'büyük', 'camcı', 'camdan', 'canavar', 'canlı',
	'casus', 'cazibe', 'cennet', 'cesur', 'ciltçi', 'ciltli', 'cımbız',
	'cinsaçı', 'civar', 'cüzdan', 'çabuk', 'çağdaş', 'çağrı', 'çakal', 'çakıl', 'çakmak',
	'çalış', 'çamaşır', 'çanak', 'çardak', 'çarpı', 'çatlak', 'çavdar',
	'çaycı', 'çaydan', 'çaylak', 'çello', 'çember', 'çengel', 'çerçeve', 'çeşit', 'çeşme', 'çevik',
	'lahmacun', 'mercimek', 'barbunya', 'patlıcan', 'ıspanak', 'brokoli', 'enginar', 'zencefil', 'zerdeçal',
	'maydanoz', 'fesleğen', 'biberiye', 'çörekotu', 'haşhaş', 'anason', 'kestane', 'kuruüzüm', 'kayısı',
	'şeftali', 'nektarin', 'mandalina', 'greyfurt', 'avokado', 'böğürtlen', 'ahududu', 'karpuz',
	'çilek', 'formül', 'pergel', 'melodi', 'virgül', 'mevsim', 'yıldız', 'öğretmen', 'mühendis',
	'hemşire', 'sanatçı', 'almanya', 'brezilya', 'ispanya', 'norveç', 'voleybol', 'süpürge', 'şifonyer',
	'manzara', 'mengene', 'şırınga', 'kavanoz', 'iskelet', 'kumanda', 'şelale', 'sindirim', 'karanfil',
	'ameliyat', 'mikrofon', 'kerpeten', 'elektrik', 'bulaşıkçı', 'buzdolabı', 'dondurucu', 'teknoloji',
	'galibiyet', 'antrenman', 'matematik', 'noktalama', 'enstrüman', 'tasarımcı', 'programcı', 'algoritma',
	'enflasyon', 'deflasyon', 'emeklilik', 'parlamento', 'demokrasi', 'medeniyet', 'psikoloji', 'sosyoloji',
	'adliye', 'akraba', 'alfabe', 'alyans', 'ananas', 'arkeolog', 'asansör', 'atölye', 'bagaj',
	'baharat', 'baklava', 'balerin', 'balina', 'bandrol', 'banknot', 'baraj', 'barış', 'baston',
	'başkan', 'başlık', 'bavul', 'bayram', 'bedava', 'belediye', 'belgesel', 'benzer', 'besin',
	'beyaz', 'biberon', 'bilgisayar', 'biletçi', 'binaen', 'birey', 'bisküvi', 'bitişik',
	'blender', 'boncuk', 'bornoz', 'botanik', 'boyacı', 'boşanma', 'boşluk', 'boğaz', 'börekçi', 'bronz',
	'burun', 'bürokrasi', 'büyükelçi', 'cankurtaran', 'cetvel',
	'tavşan', 'ayakkabı', 'eldiven', 'lacivert', 'turkuaz', 'yıldırım', 'tramvay', 'portakal', 'domates',
	'patates', 'bilardo', 'klavye', 'hoparlör', 'adaptör', 'mağara', 'leylak', 'tomurcuk',
	'lokanta', 'pastane', 'plastik', 'hastane', 'tiyatro', 'koridor', 'sandalet', 'kristal', 'komodin',
	'jaluzi', 'fonluk', 'sabunluk', 'ojelik', 'görüşürüz', 'eyvallah', 'kereviz', 'adaçayı', 'dereotu',
	'fındık', 'vişne', 'biyografi', 'coğrafya', 'çalışkan', 'danışman',
	'dayanıklı', 'deneyim', 'dizüstü', 'dondurma', 'döviz', 'düğün', 'düşünce', 'eczane', 'efsane',
	'eğitmen', 'ekonomi', 'elastik', 'elektronik', 'emekli', 'emlakçı', 'emniyet', 'enerji',
	'enfeksiyon', 'entellektüel', 'ergenlik', 'erkek', 'erzak', 'esnaf', 'eşarp', 'etkinlik', 'fabrika',
	 'fakülte', 'fantastik', 'fatura', 'federasyon', 'felaket', 'felsefe', 'festival',
	'fidanlık', 'film', 'filozof', 'finans', 'fincan', 'folklor', 'formasyon', 'fotoğraf', 'fuar',
	'futbolcu', 'galeri', 'garson', 'gazeteci', 'gecekondu', 'gelecek', 'gelenek', 'gelinlik',
	'gelişim', 'gençlik', 'genelge', 'general', 'geometri', 'gerçek', 'girişim', 'gitarist', 'gizemli',
	'gökyüzü', 'görevli', 'görgü', 'görüşme', 'gösteri', 'gözlem', 'gözlükçü', 'grafiker', 'gramer',
	'gravür', 'grup', 'gübre', 'gümrük', 'gündem', 'güneşlik', 'güvenlik', 'güzergah', 'haberci',
	'hacim', 'hademe', 'hakaret', 'hakem', 'hamile', 'hareket', 'harfiyat', 'hastabakıcı',
	'havai', 'havale', 'hayalet', 'hayran', 'hazine', 'hediye', 'hedef', 'hekim', 'hemşire',
	'atletizm', 'hentbol', 'televizyon', 'motosiklet', 'saklambaç',
	'yakartop', 'arkadaş', 'öğrenci', 'battaniye', 'gardırop', 'çiçeklik', 'çerçeve', 'aynalı',
	'dişmacunu', 'karabiber', 'çikolata', 'felsefeci', 'fotoğrafçı', 'girişimci', 'gökbilimci',
	'gözlemci', 'güzellik', 'havacılık', 'hayvanat', 'heykeltıraş', 'hidrojen', 'ihtiyaç', 'iletişim',
	'illüzyon', 'imparator', 'influencer', 'inşaatçı', 'ispirto', 'istatistik', 'işletmeci', 'itfaiyeci',
	'jeneratör', 'jeolog', 'jimnastik', 'kalorifer', 'kameraman', 'kampanya', 'kapasite', 'kapitalizm',
	'kardiyolog', 'karikatür', 'katalog', 'kategori', 'katedral', 'kaymakam', 'kütüphane', 'klarnetçi',
	'koleksiyon', 'komedyen', 'komisyon', 'kompliman', 'konservatuvar', 'konferans', 'koordinat',
	'koreograf', 'kozmetik', 'kriminolog', 'kütüphaneci', 'laborant', 'laboratuvar', 'lavanta',
	'limonata', 'literatür', 'lokomotif', 'madalyon', 'mahkeme', 'makyaj', 'malzeme', 'mandolin',
	'manifesto', 'manikür', 'marangoz', 'marmelat', 'matbaacı', 'meditasyon', 'mekanizma',
	'memuriyet', 'menajer', 'meridyen', 'meraklı', 'metalurji', 'meteor', 'metodoloji', 'mıknatıs',
	'mikroskop', 'mineral', 'minyatür', 'misafirperver', 'mobilya', 'modernizm',
	'molekül', 'monoton', 'motivasyon', 'motosikletçi', 'muhasebeci', 'muhabir', 'muhalefet', 'muhtar',
	'mücevher', 'müdür', 'müfettiş', 'mühendislik', 'müzayede', 'müzisyen', 'navigasyon', 'nezaket',
	'nöroloji', 'objektif', 'obsesif', 'okyanus', 'olimpiyat', 'operasyon', 'orkestra', 'otobiyografi',
	'karnabahar', 'tornavida', 'hayalperest',
	'apartman', 'atmosfer', 'bakteri', 'başarı', 'belgeselci', 'beysbol', 'bilimkurgu',
	'biyokimya', 'biyolog', 'botanikçi', 'coğrafyacı', 'çevirmen', 'çikolatalı',
	'dekorasyon', 'dermatolog', 'dezavantaj', 'diktatörlük', 'diplomasi', 'distribütör', 'diyabet',
	'doğaçlama', 'dokümantasyon', 'dolaşım', 'dramaturg', 'duygusallık', 'düzensizlik', 'ekolojist',
	'ekosistem', 'ekspresyonizm', 'elektrikçi', 'eleştirmen', 'endokrinolog', 'endüstri',
	'enformasyon', 'enternasyonal', 'epidemiyoloji', 'ergonomi', 'etimoloji', 'farmakoloji', 'faşizm',
	'fenomenoloji', 'filarmoni', 'filoloji', 'fizyoterapi', 'formatlama', 'fotoğrafçılık', 'fragman',
	'frekans', 'gastronomi', 'gazetecilik', 'geleneksel', 'genetikçi', 'gökbilim', 'gökdelen',
	'gösterişli', 'gözlem evi', 'grafoloji', 'gramofon', 'helikopterci', 'hemoglobin', 'hepatit',
	'heterojen', 'hiperaktif', 'hipopotam', 'hipotez', 'hissedar', 'histoloji', 'homojen',
	'hormonlar', 'hukukçu', 'içgüdüsel', 'idarecilik', 'idealizm', 'ideoloji', 'ihracatçı',
	'ihtimal', 'illüstrasyon', 'imitasyon', 'imparatorluk', 'improvizasyon', 'insaniyet', 'insiyatif',
	'inspektör', 'jenerasyon', 'jeofizik', 'jeopolitik', 'kaligrafi', 'kalorimetre', 'kanserolog',
	'kapitalist', 'karakteristik', 'karbonhidrat', 'kardiyoloji', 'karizma', 'kartpostal', 'kastanyet',
	'kataloglama', 'kemoterapi', 'kılavuzluk', 'kırtasiyeci', 'klasifikasyon', 'klimatoloji',
	'koleksiyoncu', 'kolesterol', 'kombinasyon', 'komünikasyon', 'komünizm', 'konsantrasyon',
	'konseptüel', 'konstrüksiyon'
];